export const REQUEST_MOVIES_LISTS = 'REQUEST_MOVIES_LISTS';
export const RECIEVE_MOVIES_LISTS = 'RECIEVE_MOVIES_LISTS';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const UNSELECT_MOVIE = 'UNSELECT_MOVIE';